// Cloudflare/OpenNext custom worker entrypoint.
//
// The generated OpenNext worker only exports `fetch`. Production continuity in
// Cloudflare needs a real Workers `scheduled()` handler; Vercel-style
// `vercel.json` crons are ignored by Workers deployments. This wrapper reuses
// the generated fetch handler and invokes the existing cron route handlers on
// each Cloudflare Cron Trigger.

// `.open-next/worker.js` is generated by @opennextjs/cloudflare at build/deploy
// time. It is intentionally loaded lazily: importing it at module evaluation
// time can evaluate application route modules before Kilo's Worker `env` has
// been projected into process.env, causing Redis initialization to fail before
// ensureKiloPaperFallback() has a chance to run.
type OpenNextHandler = {
  fetch(request: Request, env?: WorkerEnvironment, ctx?: WorkerExecutionContext): Promise<Response>
}

let openNextHandlerPromise: Promise<OpenNextHandler> | undefined

async function getOpenNextHandler(): Promise<OpenNextHandler> {
  if (!openNextHandlerPromise) {
    openNextHandlerPromise = import("./.open-next/worker.js").then((module) => {
      const handler = (module as { default?: OpenNextHandler }).default
      if (!handler || typeof handler.fetch !== "function") {
        throw new Error("Generated OpenNext worker does not export a fetch handler")
      }
      return handler
    })
  }
  return openNextHandlerPromise
}

type WorkerExecutionContext = {
  waitUntil?: (promise: Promise<unknown>) => void
  passThroughOnException?: () => void
}

type WorkerScheduledController = {
  cron?: string
  scheduledTime?: number
}

type WorkerEnvironment = {
  CRON_SECRET?: string
  NEXT_PUBLIC_APP_URL?: string
  DEPLOYMENT_URL?: string
  [key: string]: unknown
}

function registerWorkerDatabaseBinding(env: WorkerEnvironment): void {
  // Some Cloudflare-compatible providers expose SQLite as a Worker binding
  // instead of DB_URL/DB_TOKEN. Keep the binding out of process.env and pass
  // it through the shared global bridge consumed by the SQL adapter.
  const candidate = Object.entries(env ?? {}).find(([key, value]) =>
    /^(?:DB|KILO_DB|CTS_DB|DATABASE)$/i.test(key) && value && typeof value === "object" &&
    typeof (value as { prepare?: unknown }).prepare === "function",
  )?.[1]
  if (candidate && typeof (globalThis as any).__cts_kilo_sqlite_binding === "undefined") {
    ;(globalThis as any).__cts_kilo_sqlite_binding = candidate
  }
}

const CRON_PATHS = [
  "/api/cron/server-continuity",
  "/api/cron/sync-live-positions",
] as const

function exposeWorkerEnvironment(env: WorkerEnvironment): void {
  // CTS's persistence/runtime modules intentionally use process.env so the
  // same code works on Node, Vercel, and self-hosted servers. Cloudflare
  // exposes bindings only through the Worker env argument, however. Project
  // primitive bindings into the Node-compat environment before OpenNext loads
  // a request route; otherwise Kilo silently behaves as if its Redis/DB and
  // paper-fallback flags were absent.
  if (typeof process === "undefined" || !process.env) return
  for (const [key, value] of Object.entries(env ?? {})) {
    if (typeof value !== "string" && typeof value !== "number" && typeof value !== "boolean") continue
    process.env[key] = String(value)
  }
}

function ensureKiloPaperFallback(request: Request | undefined, env: WorkerEnvironment): void {
  // Kilo's deploy wrapper has historically omitted `vars` from the runtime
  // object even though they are present in wrangler.jsonc.  That made the
  // application enter the old production Redis hard-failure path before the
  // first migration.  Establish the safe, process-local paper mode at the
  // Worker boundary when no durable backend is supplied.  This never enables
  // live orders: the separate live-trade gate remains explicitly disabled.
  const host = (() => {
    try {
      return new URL(request?.url || String(env?.NEXT_PUBLIC_APP_URL || env?.DEPLOYMENT_URL || "")).hostname
    } catch {
      return ""
    }
  })()
  const kilo =
    /(^|\.)kiloapps\.io$/i.test(host) ||
    String(env?.CTS_DEPLOYMENT_RUNTIME || "").toLowerCase().startsWith("kilo") ||
    String(env?.KILO_DEPLOYMENT || "") === "1" ||
    (typeof process !== "undefined" ? String(process.env?.CTS_DEPLOYMENT_RUNTIME || "") : "").toLowerCase().startsWith("kilo")
  if (!kilo || typeof process === "undefined" || !process.env) return

  const hasDurableBackend = Boolean(
    process.env.REDIS_URL || process.env.KV_URL ||
    (process.env.UPSTASH_REDIS_REST_URL && process.env.UPSTASH_REDIS_REST_TOKEN) ||
    (process.env.KV_REST_API_URL && process.env.KV_REST_API_TOKEN) ||
    (process.env.DB_URL && process.env.DB_TOKEN) ||
    (process.env.KILO_DB_URL && process.env.KILO_DB_TOKEN) ||
    (process.env.KILO_DATABASE_URL && (process.env.KILO_DB_TOKEN || process.env.KILO_DATABASE_TOKEN)),
  )
  if (hasDurableBackend) return
  if (process.env.ALLOW_PROD_INLINE_REDIS === "0") return
  process.env.CTS_DEPLOYMENT_RUNTIME ||= "kilo-deploy"
  process.env.KILO_DEPLOYMENT ||= "1"
  process.env.ALLOW_PROD_INLINE_REDIS ||= "1"
  process.env.ALLOW_INLINE_REDIS_LIVE_TRADING = "0"
  process.env.DISABLE_IN_PROCESS_CONTINUITY ||= "1"
  process.env.DISABLE_TRADE_ENGINE_IN_PROCESS ||= "1"
}

async function invokeCronPath(path: (typeof CRON_PATHS)[number], env: WorkerEnvironment, _ctx: WorkerExecutionContext): Promise<void> {
  const cronSecret = String(env?.CRON_SECRET || "").trim()
  if (cronSecret.length < 16) {
    throw new Error("CRON_SECRET is missing or too short; scheduled continuity is fail-closed")
  }
  const rawOrigin = String(env?.NEXT_PUBLIC_APP_URL || env?.DEPLOYMENT_URL || "").trim()
  let origin: URL
  try {
    origin = new URL(rawOrigin)
  } catch {
    throw new Error("NEXT_PUBLIC_APP_URL (or DEPLOYMENT_URL) must be configured for scheduled continuity")
  }
  const loopback = origin.hostname === "127.0.0.1" || origin.hostname === "localhost" || origin.hostname === "::1"
  if (origin.protocol !== "https:" && !(origin.protocol === "http:" && loopback)) {
    throw new Error("Scheduled continuity requires an HTTPS public deployment URL")
  }

  const request = new Request(new URL(path, origin), {
    method: "GET",
    headers: {
      "User-Agent": "cloudflare-scheduled-worker",
      "x-cloudflare-cron": "1",
      ...(cronSecret ? { Authorization: `Bearer ${cronSecret}` } : {}),
    },
  })

  // Re-enter OpenNext with the real deployment origin. OpenNext validates the
  // request host; an invented internal hostname fails before route dispatch.
  // Calling the generated handler avoids an external network round-trip and
  // preserves the same worker environment/shared Redis bindings.
  const response = await (await getOpenNextHandler()).fetch(request, env, _ctx)
  if (!response.ok) {
    const text = await response.text().catch(() => "")
    throw new Error(`${path} failed with ${response.status}${text ? `: ${text.slice(0, 500)}` : ""}`)
  }
}

export default {
  // Kilo preview/runtime invocations can call a Worker fetch handler without
  // an explicit env or execution-context object. OpenNext enumerates env while
  // creating its request context; passing undefined makes every route fail
  // before middleware or the application can respond. Missing bindings remain
  // visible to startup/readiness and never enable live orders.
  async fetch(request: Request, env?: WorkerEnvironment, ctx?: WorkerExecutionContext) {
    const runtimeEnv = env ?? {}
    exposeWorkerEnvironment(runtimeEnv)
    registerWorkerDatabaseBinding(runtimeEnv)
    ensureKiloPaperFallback(request, runtimeEnv)
    return (await getOpenNextHandler()).fetch(request, runtimeEnv, ctx ?? {})
  },

  async scheduled(_controller: WorkerScheduledController, env: WorkerEnvironment, ctx: WorkerExecutionContext) {
    console.log("[CTS-K-N scheduled continuity] event received")
    const runtimeEnv = env ?? {}
    exposeWorkerEnvironment(runtimeEnv)
    registerWorkerDatabaseBinding(runtimeEnv)
    ensureKiloPaperFallback(undefined, runtimeEnv)
    const work = Promise.allSettled(CRON_PATHS.map((path) => invokeCronPath(path, runtimeEnv, ctx ?? {}))).then((results) => {
      const failures = results.filter((result): result is PromiseRejectedResult => result.status === "rejected")
      if (failures.length > 0) {
        const message = failures
          .map((failure) => (failure.reason instanceof Error ? failure.reason.message : String(failure.reason)))
          .join("; ")
        console.error(`[CTS-K-N scheduled continuity] ${message}`)
        throw new Error(message)
      }
    })

    // Scheduled handlers should extend their lifetime with waitUntil. This also
    // avoids a local-workerd self-fetch deadlock caused by awaiting a nested
    // request to the same worker before the ScheduledEvent can yield.
    if (ctx.waitUntil) {
      ctx.waitUntil(work)
      return
    }
    await work
  },
}

// Re-export generated OpenNext Durable Objects if present. OpenNext documents
// this as required when an app uses its DO queue/tag-cache features.
// @ts-ignore `.open-next/worker.js` is generated by @opennextjs/cloudflare.
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js"
