}

let openNextHandlerPromise: Promise<OpenNextHandler> | undefined

async function getOpenNextHandler(): Promise<OpenNextHandler> {
  if (!openNextHandlerPromise) {
    // The provider generates `.open-next/worker.js` after the repository
    // typecheck. The ambient declaration in types/open-next-worker.d.ts covers
    // normal resolution; the local ignore also keeps this boundary compatible
    // with older server checkouts that do not yet include that declaration.
    // @ts-ignore generated by @opennextjs/cloudflare during kilo:build
    openNextHandlerPromise = import("./.open-next/worker.js").then((module) => {
      const handler = (module as { default?: OpenNextHandler }).default
      if (!handler || typeof handler.fetch !== "function") {
        throw new Error("Generated OpenNext worker does not export a fetch handler")
      }
      return handler
    })
  }
// Cloudflare/OpenNext custom worker entrypoint.
//
// The generated OpenNext worker only exports `fetch`. Production continuity in
// Cloudflare needs a real Workers `scheduled()` handler; Vercel-style
// `vercel.json` crons are ignored by Workers deployments. This wrapper reuses
// the generated fetch handler and invokes the existing cron route handlers on
// each Cloudflare Cron Trigger.

// `.open-next/worker.js` is generated by @opennextjs/cloudflare at build/deploy
// time. It is intentionally loaded lazily: importing it at module evaluation
// time can evaluate application route modules before Kilo's Worker `env` has
// been projected into process.env, causing Redis initialization to fail before
// ensureKiloPaperFallback() has a chance to run.
type OpenNextHandler = {
  fetch(request: Request, env?: WorkerEnvironment, ctx?: WorkerExecutionContext): Promise<Response>
}

let openNextHandlerPromise: Promise<OpenNextHandler> | undefined

async function getOpenNextHandler(): Promise<OpenNextHandler> {
  if (!openNextHandlerPromise) {
    // The provider generates `.open-next/worker.js` after the repository
    // typecheck. The ambient declaration in types/open-next-worker.d.ts covers
    // normal resolution; the local ignore also keeps this boundary compatible
    // with older server checkouts that do not yet include that declaration.
    // @ts-ignore generated by @opennextjs/cloudflare during kilo:build
    openNextHandlerPromise = import("./.open-next/worker.js").then((module) => {
      const handler = (module as { default?: OpenNextHandler }).default
      if (!handler || typeof handler.fetch !== "function") {
        throw new Error("Generated OpenNext worker does not export a fetch handler")
      }
      return handler
    })
  }
  return openNextHandlerPromise
}

type WorkerExecutionContext = {
  waitUntil?: (promise: Promise<unknown>) => void
  passThroughOnException?: () => void
}

type WorkerScheduledController = {
  cron?: string
  scheduledTime?: number
}

type WorkerEnvironment = {
  CRON_SECRET?: string
  NEXT_PUBLIC_APP_URL?: string
  DEPLOYMENT_URL?: string
  [key: string]: unknown
}

function registerWorkerDatabaseBinding(env: WorkerEnvironment): void {
  // Some Cloudflare-compatible providers expose SQLite as a Worker binding
  // instead of DB_URL/DB_TOKEN. Keep the binding out of process.env and pass
  // it through the shared global bridge consumed by the SQL adapter.
  const candidate = Object.entries(env ?? {}).find(([key, value]) =>
    /^(?:DB|KILO_DB|CTS_DB|DATABASE)$/i.test(key) && value && typeof value === "object" &&
    typeof (value as { prepare?: unknown }).prepare === "function",
  )?.[1]
  if (candidate && typeof (globalThis as any).__cts_kilo_sqlite_binding === "undefined") {
    ;(globalThis as any).__cts_kilo_sqlite_binding = candidate
  }
}

const CRON_PATHS = [
  "/api/cron/server-continuity",
  "/api/cron/sync-live-positions",
] as const

function exposeWorkerEnvironment(env: WorkerEnvironment): void {
  // CTS's persistence/runtime modules intentionally use process.env so the
  // same code works on Node, Vercel, and self-hosted servers. Cloudflare
  // exposes bindings only through the Worker env argument, however. Project
  // primitive bindings into the Node-compat environment before OpenNext loads
  // a request route; otherwise Kilo silently behaves as if its Redis/DB and
  // paper-fallback flags were absent.
  if (typeof process === "undefined" || !process.env) return
  for (const [key, value] of Object.entries(env ?? {})) {
    if (typeof value !== "string" && typeof value !== "number" && typeof value !== "boolean") continue
    process.env[key] = String(value)
  }
}

function ensureKiloPaperFallback(request: Request | undefined, env: WorkerEnvironment): void {
  // Kilo's deploy wrapper has historically omitted `vars` from the runtime
  // object even though they are present in wrangler.jsonc.  That made the
  // application enter the old production Redis hard-failure path before the
  // first migration.  Establish the safe, process-local paper mode at the
  // Worker boundary when no durable backend is supplied.  This never enables
  // live orders: the separate live-trade gate remains explicitly disabled.
  const host = (() => {
    try {
      return new URL(request?.url || String(env?.NEXT_PUBLIC_APP_URL || env?.DEPLOYMENT_URL || "")).hostname
    } catch {
      return ""
    }
  })()
  const kilo =
    /(^|\.)kiloapps\.io$/i.test(host) ||
    String(env?.CTS_DEPLOYMENT_RUNTIME || "").toLowerCase().startsWith("kilo") ||
    String(env?.KILO_DEPLOYMENT || "") === "1" ||
    (typeof process !== "undefined" ? String(process.env?.CTS_DEPLOYMENT_RUNTIME || "") : "").toLowerCase().startsWith("kilo")
  if (!kilo || typeof process === "undefined" || !process.env) return

  const hasDurableBackend = Boolean(
    process.env.REDIS_URL || process.env.KV_URL ||
    (process.env.UPSTASH_REDIS_REST_URL && process.env.UPSTASH_REDIS_REST_TOKEN) ||
    (process.env.KV_REST_API_URL && process.env.KV_REST_API_TOKEN) ||
    (process.env.DB_URL && process.env.DB_TOKEN) ||
    (process.env.KILO_DB_URL && process.env.KILO_DB_TOKEN) ||
    (process.env.KILO_DATABASE_URL && (process.env.KILO_DB_TOKEN || process.env.KILO_DATABASE_TOKEN)),
  )
  if (hasDurableBackend) return
  if (process.env.ALLOW_PROD_INLINE_REDIS === "0") return
  // Some Worker runtimes expose a compatibility `process.env` object whose
  // writes are not visible to modules bundled by OpenNext. Keep the decision
  // on globalThis as well so the Redis backend selector sees the same
