import fs from "node:fs"
import path from "node:path"

const root = process.cwd()
const read = (file: string) => fs.readFileSync(path.join(root, file), "utf8")

describe("coherent strategy snapshots and schema v107", () => {
  test("uses symbol-local active lineage under parallel symbol processing", () => {
    const source = read("lib/strategy-coordinator.ts")
    expect(source).toContain("private _activeKeysCache = new Map<string")
    expect(source).toContain("this._activeKeysCache.set(symbol")
    expect(source).toContain("this._activeKeysCache.get(symbol)")
    expect(source).not.toContain("private _activeKeysCache: { keys: Set<string>")
  })

  test("writes Real and Live activity atomically from one snapshot", () => {
    const source = read("lib/strategy-coordinator.ts")
    expect(source).toContain("coordinateActiveRealLiveCounts")
    expect(source).toContain("coherentActiveCounts.real")
    expect(source).toContain("coherentActiveCounts.live")
    expect(source).toContain("`${symbol}:snapshot:ts`")
    expect(source).not.toContain("dev fallback - injected synthetic qualifying set from MAIN")

    const stats = read("app/api/connections/progression/[id]/stats/route.ts")
    expect(stats).toContain("Do not clamp stage snapshots against each other")
    expect(stats).not.toContain("if (stratCounts.live > stratCounts.real)")
  })

  test("mirrors every strategy-stage progression mutation into the active engine scope", () => {
    const source = read("lib/strategy-coordinator.ts")
    expect(source).toContain('buildProgressionScope(connectionId, "main")')
    expect(source).toContain("hsetStrategyProgression")
    expect(source).toContain("hincrbyStrategyProgression")
    expect(source).toContain("expireStrategyProgression")
    expect(source).toContain('hincrbyStrategyProgression(client, this.connectionId, "strategies_main_cycles",          1)')
    expect(source).not.toContain('const redisKey = `progression:${this.connectionId}`')
  })

  test("persists bounded v3 runtime projections and fails closed after restart", () => {
    const source = read("lib/strategy-coordinator.ts")
    expect(source).toContain("formatVersion: 3")
    expect(source).toContain("runtimeProjection: true")
    expect(source).toContain("projectRuntimeStageRows")
    expect(source).toContain("strategySetStorageRef")
    expect(source).toContain("sourceRef")
    expect(source).toContain("hydrateStrategySetSnapshots")
    expect(source).toContain("Legacy v1 stored only Set keys")
  })

  test("migrations are sequential through the coherent schema", () => {
    const source = read("lib/redis-migrations.ts")
    const versions = Array.from(source.matchAll(/version:\s*(\d+)/g), (match) => Number(match[1]))
    expect(versions.at(-1)).toBe(107)
    expect(versions.every((version, index) => version === index + 1)).toBe(true)
    expect(source).toContain('name: "075-bound-high-frequency-statistics-storage"')
    expect(source).toContain('name: "079-repair-hourly-statistics-rollups"')
    expect(source).toContain('name: "080-index-exact-strategy-set-ledgers-and-minute-snapshots"')
    expect(source).toContain('name: "081-seed-independent-block-profit-factor-ratio"')
    expect(source).toContain('name: "082-normalize-live-minimum-ratio-and-position-cost"')
    expect(source).toContain('name: "083-enforce-identity-live-volume-ratios"')
    expect(source).toContain('name: "084-freeze-base-volume-coordination-at-identity"')
    expect(source).toContain('name: "085-main-trade-position-cost-ratio-four-stage"')
    expect(source).toContain('name: "086-exhaustive-indication-base-and-block-only-defaults"')
    expect(source).toContain('name: "087-signal-bootstrap-direction-lanes-and-strategy-rows"')
    expect(source).toContain('name: "088-repair-exhaustive-indications-signal-capacity-and-stage-caps"')
    expect(source).toContain('name: "089-signal-full-source-cycle-and-base-pf-floor"')
    expect(source).toContain('name: "090-base-valid-and-signal-admission-contract"')
    expect(source).toContain('name: "091-unlimited-stage-rows-cadence-and-block-work-scheduler"')
    expect(source).toContain('name: "092-exact-indication-cadence-and-unlimited-preset-types"')
    expect(source).toContain('name: "093-pf-floor-and-continuous-row-live-defaults"')
    expect(source).toContain('name: "094-expand-block-count-defaults-to-canonical-twelve"')
    expect(source).toContain('name: "095-active-outbreak-ranges-and-market-protection-profiles"')
    expect(source).toContain('name: "097-enforce-canonical-mandatory-symbol-basket"')
    expect(source).toContain('name: "102-credential-injection-live-safety-and-index-repair"')
    expect(source).toContain('name: "103-systemwide-position-cost-pf-selection-coordinate"')
    expect(source).toContain('name: "104-minimum-executable-volumes-and-set-protection"')
    expect(source).toContain('name: "105-forex-market-coordination-and-instaforex-defaults"')
    expect(source).toContain('name: "106-compound-block-steps-and-neutral-pf-factor"')
    expect(source).toContain('name: "107-base-pf-and-real-live-row-defaults"')
    expect(source).toContain('strategy_set_listing_indexes: "lifetime-active-closed"')
    expect(source).toContain('inline_snapshot_interval_ms: "60000"')
    expect(source).toContain('independent_block_profit_factor: "neutral-distance-x-ratio-x-volume-increment-v2"')
    expect(source).toContain('block_profit_factor_ratio_default: "1.1"')
    expect(source).toContain('block_increment_steps_default: "2"')
    expect(source).toContain('high_frequency_statistics_storage: "bounded-hourly-rollups-v2"')
    expect(source).toContain('name: "076-dynamic-symbol-selection-default-one"')
    expect(source).toContain('name: "077-indexed-current-indication-snapshots"')
    expect(source).toContain('name: "078-coherent-strategy-set-snapshots"')
    expect(source).toContain('strategy_active_snapshot: "symbol-local-atomic-real-live-v2"')
    expect(source).toContain('strategy_real_snapshot: "bounded-derived-scalars-v2"')
  })

  test("stats ignore stale fields outside the durable symbol basket", () => {
    const source = read("app/api/connections/progression/[id]/stats/route.ts")
    expect(source).toContain("activeStatsSymbolFilter")
    expect(source).toContain("!activeStatsSymbolFilter.has(fieldSymbol)")
    expect(source).toContain("aggregateIndicationSnapshot(")
    expect(source).toContain("indication_sets_active:${connectionId}")
    expect(source).toContain("indicationsEvaluated:")
    expect(source).toContain('metric === "evaluated"')
  })
})
